import type { Banner } from "./types";

// The answer space for Find Your Banner: curated archetypes, each mapped to a
// real game system + faction. All prose is original; faction and system
// names are used nominatively. Image prompts describe environments and mood
// only — no characters, no publisher IP.

export const BANNERS: Banner[] = [
  {
    id: "shield-unbroken",
    name: "The Shield Unbroken",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Space Marines",
    profile: { discipline: 3, valor: 2, endurance: 2 },
    personalitySummary:
      "You are the one people look to when everything goes wrong. You don't panic, you don't posture — you plant your feet and the chaos breaks around you like water on stone.",
    reasoning:
      "You'd thrive in Warhammer 40,000, where grand heroics meet grim odds — and the Space Marines are its steadfast heart: disciplined, loyal, and unbreakable when it matters most. Their armies reward players who hold the line and strike with purpose.",
    chronicleIntro:
      "The chronicle opens on a wall that should have fallen a hundred years ago. It still stands. So do you. Somewhere beyond the smoke, a horn sounds — and you take one step forward, because someone has to be first.",
    imagePrompt:
      "A colossal marble bastion on a cliff edge at dawn, gold light breaking through storm clouds, banners of deep blue snapping in the wind, embers rising from distant fires below, monumental and unyielding, painterly, no people",
    cardQuote: "Someone has to be first.",
    palette: ["#0c1425", "#1e3a5f", "#d4ac62"],
  },
  {
    id: "burning-faith",
    name: "The Burning Faith",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Adepta Sororitas",
    profile: { wonder: 3, valor: 2, discipline: 1 },
    personalitySummary:
      "You believe in things fully or not at all. When you commit — to a person, a cause, an idea — you burn for it, and people around you warm their hands on that fire whether they admit it or not.",
    reasoning:
      "Warhammer 40,000 is a setting where conviction is a weapon, and no one wields it like the Adepta Sororitas — warriors whose faith is literal armor. Their armies reward the player who commits utterly and never takes a backward step.",
    chronicleIntro:
      "The chronicle opens in candlelight. A thousand small flames, each one a promise somebody kept. You add yours to the constellation and the dark leans away — not because it fears the light, but because it fears the one who lit it.",
    imagePrompt:
      "A vast ruined cathedral interior lit by thousands of candles, crimson and gold light on broken stained glass, incense smoke curling into high shadowed vaults, solemn and radiant, painterly, no people",
    cardQuote: "The dark leans away.",
    palette: ["#1a0a0a", "#5f1e1e", "#e5c988"],
  },
  {
    id: "endless-hunger",
    name: "The Endless Hunger",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Tyranids",
    profile: { wildness: 3, cunning: 2, endurance: 1 },
    personalitySummary:
      "You don't do things halfway. When something catches your interest you consume it whole — every book, every video, every rabbit hole at 2 a.m. People call it obsession. You call it Tuesday.",
    reasoning:
      "Warhammer 40,000 gives you a whole galaxy to devour, and the Tyranids are appetite made into an army — a living tide that adapts, evolves, and overwhelms. They reward players who think like an ecosystem instead of a general.",
    chronicleIntro:
      "The chronicle opens under a sky with two moons, in a jungle that is quietly rearranging itself. Everything here is patient. Everything here is hungry. You feel strangely at home.",
    imagePrompt:
      "An alien jungle beneath twin moons, bioluminescent violet and green flora, strange organic spires in the mist, air thick with drifting spores, beautiful and unsettling, painterly, no people",
    cardQuote: "Everything here is patient. Everything here is hungry.",
    palette: ["#120a1a", "#3d1e5f", "#7ee08a"],
  },
  {
    id: "deathless-crown",
    name: "The Deathless Crown",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Necrons",
    profile: { endurance: 3, discipline: 2, cunning: 2 },
    personalitySummary:
      "You play the long game. While everyone else reacts, you're already three moves ahead, unbothered, sipping something. Time is not your enemy — it's your instrument.",
    reasoning:
      "In Warhammer 40,000 the Necrons are patience given a metal body: an empire that simply waited out the ages and woke up still owning everything. Their armies reward calm, inevitability, and the confidence of a plan measured in eons.",
    chronicleIntro:
      "The chronicle opens on a desert where monoliths older than the stars are shrugging off the sand. Nothing here hurries. Nothing here needs to. The dynasty does not return — it resumes.",
    imagePrompt:
      "Black desert monoliths emerging from endless dunes at night, geometric emerald light tracing ancient carved circuitry, cold stars overhead, vast and silent, painterly, no people",
    cardQuote: "The dynasty does not return — it resumes.",
    palette: ["#050d0a", "#0f3d2e", "#3de8a0"],
  },
  {
    id: "roaring-horde",
    name: "The Roaring Horde",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Orks",
    profile: { valor: 3, wildness: 3 },
    personalitySummary:
      "You bring the noise. Every group has one person who makes things happen through sheer momentum and infectious chaos — that's you, and honestly, the plan usually works because nobody told you it couldn't.",
    reasoning:
      "Warhammer 40,000 has room for glorious mayhem, and the Orks are its beating, bellowing heart — a culture where enthusiasm is technology and the biggest laugh wins. Their armies reward speed, audacity, and joy.",
    chronicleIntro:
      "The chronicle opens mid-charge. There was probably a plan at some point. It doesn't matter now. The horizon is on fire, everyone is shouting, and you have never felt more alive.",
    imagePrompt:
      "A scrap-iron war camp at sunset under a smoke-red sky, towering junk totems and patchwork banners, sparks and bonfire light, raucous energy in every silhouette of machinery, painterly, no people",
    cardQuote: "There was probably a plan at some point.",
    palette: ["#140d05", "#5f3a1e", "#8ad46a"],
  },
  {
    id: "veiled-path",
    name: "The Veiled Path",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Aeldari",
    profile: { cunning: 3, wonder: 2 },
    personalitySummary:
      "You see the board, not the piece. People think you're quiet; really you're listening, weighing, and choosing the exact moment when one precise word — or move — changes everything.",
    reasoning:
      "Warhammer 40,000 rewards foresight, and no one embodies it like the Aeldari — an ancient people who read fate like sheet music and strike only where it matters. Their armies are fast, fragile, and devastating in the hands of a player who plans two turns ahead.",
    chronicleIntro:
      "The chronicle opens on a path only you can see, silver-thin, threading between disasters that haven't happened yet. You've already counted the exits. You always do.",
    imagePrompt:
      "Elegant glass spires drifting through a sea of stars, pale opal light refracting through crystalline architecture, ribbons of aurora, serene and melancholy, painterly, no people",
    cardQuote: "You've already counted the exits.",
    palette: ["#0a0f1a", "#2e3a5f", "#c9d8f0"],
  },
  {
    id: "verdant-wrath",
    name: "The Verdant Wrath",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Sylvaneth",
    profile: { wildness: 3, wonder: 2, endurance: 1 },
    personalitySummary:
      "You're gentle until you're not. People mistake your calm for softness, right up until something you love is threatened — then they learn why forests outlive empires.",
    reasoning:
      "Age of Sigmar is high fantasy turned up to myth, and the Sylvaneth are its wild soul — spirits of root and thorn who sing groves into existence and enemies into the earth. They reward players who cultivate the board like a garden, then harvest.",
    chronicleIntro:
      "The chronicle opens in a forest that remembers everything. Every kindness, every axe. Today the canopy stirs without wind, and the old wrath rises through the roots like sap in spring — patient, green, and absolutely certain.",
    imagePrompt:
      "An ancient forest waking at green dawn, colossal moss-covered trees with faint golden spirit-light between the roots, drifting seeds glowing like embers, mist and shafts of light, painterly, no people",
    cardQuote: "Forests outlive empires.",
    palette: ["#08120a", "#1e4a2e", "#a0e87e"],
  },
  {
    id: "storms-herald",
    name: "The Storm's Herald",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Stormcast Eternals",
    profile: { valor: 3, wonder: 2, discipline: 1 },
    personalitySummary:
      "You show up. When the group chat goes silent and the plan falls apart, you're the one who appears — slightly dramatic, fully committed, exactly when it matters. You'd rather burn out saving something than rust guarding it.",
    reasoning:
      "Age of Sigmar opens with heroes cast down from the sky in lightning, and that's the Stormcast Eternals' whole covenant: arrive like thunder, stand where others fell. Their armies are forgiving to learn and heroic to play — the classic first banner for a reason.",
    chronicleIntro:
      "The chronicle opens with a storm that chooses. Out of every soul on the field, the lightning bends — and finds you. Falling upward feels, briefly, like being remembered by the sky.",
    imagePrompt:
      "Lightning striking a mountain temple above the clouds at dusk, gold and cobalt storm light, colossal stone stairways vanishing into cloud, rain frozen mid-fall, mythic and electric, painterly, no people",
    cardQuote: "Arrive like thunder.",
    palette: ["#0a0d1a", "#2e2a5f", "#f0d878"],
  },
  {
    id: "iron-oath",
    name: "The Iron Oath",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Leagues of Votann",
    profile: { endurance: 3, discipline: 2, cunning: 1 },
    personalitySummary:
      "Your word is load-bearing. You're the friend who actually shows up with the truck, the one who finishes what everyone else abandoned. Flash fades; you were built for the long haul.",
    reasoning:
      "In Warhammer 40,000 the Leagues of Votann are the galaxy's stubbornest survivors — clans of miners and makers whose grudges are ledgers and whose loyalty is bedrock. Their armies reward methodical players who advance like a glacier and give back nothing.",
    chronicleIntro:
      "The chronicle opens in a forge-hall under a mountain of ice, where every hammer-fall is a promise kept. The ancestors are listening. You pick up the hammer.",
    imagePrompt:
      "Vast forge-halls carved beneath a mountain of ice, rivers of molten copper light between dark stone pillars, northern lights visible through a distant cavern mouth, warm fire against deep cold, painterly, no people",
    cardQuote: "Your word is load-bearing.",
    palette: ["#0d0f12", "#3d2e1e", "#e8a05f"],
  },
  {
    id: "machine-communion",
    name: "The Machine Communion",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Adeptus Mechanicus",
    profile: { discipline: 2, wonder: 2, cunning: 2 },
    personalitySummary:
      "You want to know how it works — the clock, the code, the universe. Taking things apart is your love language, and there's a quiet ecstasy in the moment a system finally makes sense.",
    reasoning:
      "Warhammer 40,000's Adeptus Mechanicus treat knowledge itself as sacred — engineers, archivists, and priests of the machine in one crimson procession. Their armies reward optimizers: every unit a component, every battle a proof.",
    chronicleIntro:
      "The chronicle opens in a city that hums in a frequency only you seem to hear. Somewhere beneath the brass and steam, a great engine is asking a question. You intend to answer it.",
    imagePrompt:
      "A forge-city of brass pipes and sacred machinery beneath a rust-red sky, geometric processional avenues lit by furnace glow and green data-light, steam rising past cog-shaped spires, intricate and reverent, painterly, no people",
    cardQuote: "Knowledge is the only heirloom.",
    palette: ["#120808", "#5f1e1e", "#7ec9c0"],
  },
  {
    id: "midnight-court",
    name: "The Midnight Court",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Soulblight Gravelords",
    profile: { cunning: 2, endurance: 2, wonder: 2 },
    personalitySummary:
      "You have excellent taste and terrifying patience. You collect — books, grudges, beautiful things — and you never forget a detail. Charm is your opening move; the endgame is always yours.",
    reasoning:
      "Age of Sigmar's Soulblight Gravelords are aristocracy that refused to end: elegant, ancient, and always owed a debt. Their armies reward players who bleed opponents slowly and command the board like a manor they've owned for centuries.",
    chronicleIntro:
      "The chronicle opens at a manor above a sea of mist, where the candles never quite go out and the portraits are all, on close inspection, of you. The invitation was written before you were born. You attend anyway.",
    imagePrompt:
      "A moonlit gothic manor on a crag above a sea of rolling mist, warm candlelight in tall windows against cold blue night, iron gates and wild roses, elegant decay, painterly, no people",
    cardQuote: "The endgame is always yours.",
    palette: ["#0a0a12", "#2e1e3d", "#c9a0d8"],
  },
  {
    id: "cracked-moon",
    name: "The Cracked Moon",
    primaryFaction: "Gloomspite Gitz",
    officialUrl: "https://www.warhammer-community.com/en-gb/topics/gloomspite-gitz/",
    officialSource: "warhammer-community",
    gameSystem: "Warhammer Age of Sigmar",
    publisher: "Games Workshop",
    profile: { cunning: 3, wildness: 2 },
    personalitySummary:
      "You are chaos with a plan — or at least a punchline. You zig when the world expects zag, and your best ideas arrive at the worst possible moments, which is precisely why they work.",
    reasoning:
      "Age of Sigmar's Gloomspite Gitz fight by moonlight, mushroom, and mischief — an ambush culture that wins by being exactly as unhinged as everyone feared. Their armies reward improvisation and reward laughing about it after.",
    chronicleIntro:
      "The chronicle opens in a cavern of glowing mushrooms under a moon with a crack in it. Everything down here is a joke, a trap, or both. You fit right in, and that should worry someone.",
    imagePrompt:
      "A vast cavern of towering bioluminescent mushrooms in blues and violets, pale crooked moonlight spilling through a crack in the cavern roof, winding paths and spore-light, whimsical and eerie, painterly, no people",
    cardQuote: "A joke, a trap, or both.",
    palette: ["#0d0a14", "#3d2e5f", "#8ae0d4"],
  },

  // Expansion batch: additive banners appended after the original twelve.
  {
    id: "blackened-choir",
    name: "The Blackened Choir",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Chaos Space Marines",
    profile: { valor: 2, cunning: 2, wildness: 2 },
    personalitySummary: "You are ambition with a soundtrack. You know the old rules well enough to break them beautifully, and you would rather be feared for becoming yourself than praised for staying small.",
    reasoning: "Warhammer 40,000 suits your taste for grand defiance, and Chaos Space Marines turn rebellion into a dark art: forceful, theatrical, and dangerous when guided by a player who likes pressure with a plan.",
    chronicleIntro: "The chronicle opens in a shattered amphitheater where every echo sounds like a vow. The old banners have burned. In the ash, a louder song begins.",
    imagePrompt: "A shattered obsidian amphitheater beneath a bruised red sky, black banners hanging from broken arches, ember-lit marble, ash drifting through crimson haze, ominous and operatic, painterly, no people",
    cardQuote: "A louder song begins.",
    palette: ["#10070a", "#3d1020", "#d14a32"],
  },
  {
    id: "lantern-line",
    name: "The Lantern Line",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Astra Militarum",
    profile: { discipline: 2, endurance: 2, valor: 2 },
    personalitySummary: "You are practical courage. Not the kind that poses for murals — the kind that checks on everyone, tightens the last strap, and keeps walking because the line needs you.",
    reasoning: "The Astra Militarum fit players who respect grit, numbers, and stubborn coordination. Their strength is not invulnerability; it is ordinary resolve multiplied until the impossible has to negotiate.",
    chronicleIntro: "The chronicle opens in rain and trench-lantern light. Somewhere ahead, the horizon grumbles. Someone laughs too quietly, someone says hold, and you do.",
    imagePrompt: "Rain-soaked defensive earthworks at night, rows of warm lanterns receding into fog, muddy parapets, distant searchlights under iron clouds, grounded and resolute, painterly, no people",
    cardQuote: "Ordinary resolve, multiplied.",
    palette: ["#0b1010", "#2f3a28", "#d6b36a"],
  },
  {
    id: "patient-horizon",
    name: "The Patient Horizon",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "T'au Empire",
    profile: { discipline: 2, wonder: 2, cunning: 1 },
    personalitySummary: "You prefer clean answers, shared purpose, and a future that is designed instead of inherited. You are at your best when the whole team moves like one considered thought.",
    reasoning: "The T'au Empire rewards a commander who values positioning, focus, and coordinated force. Their appeal is the feeling of a distant plan arriving exactly on schedule.",
    chronicleIntro: "The chronicle opens on a dawn plain of white towers and blue mist. Across the horizon, signal lights blink in sequence. The future does not charge; it aligns.",
    imagePrompt: "Sleek white observatory towers on a blue dawn plain, clean geometric terraces, misty horizon, soft amber signal lights, calm and futuristic, painterly, no people",
    cardQuote: "The future aligns.",
    palette: ["#07131a", "#1e4f66", "#f0b86a"],
  },
  {
    id: "glass-knife",
    name: "The Glass Knife",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Drukhari",
    profile: { cunning: 3, wildness: 1, valor: 1 },
    personalitySummary: "You are elegance with an exit plan. You enjoy speed, leverage, and the exact second when confidence becomes overconfidence in someone else.",
    reasoning: "Drukhari suit players who like precision, tempo, and risk sharpened to a point. They do not win by being safe; they win by making unsafe look effortless.",
    chronicleIntro: "The chronicle opens on a city of black glass bridges over a bottomless violet gulf. Every reflection smiles half a second late. You keep moving.",
    imagePrompt: "A night city of black glass bridges suspended over a violet abyss, razor-thin spires, cold neon glints, impossible depth and predatory elegance, painterly, no people",
    cardQuote: "Elegance with an exit plan.",
    palette: ["#070711", "#30164f", "#73f0d8"],
  },
  {
    id: "subterranean-star",
    name: "The Subterranean Star",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Genestealer Cults",
    profile: { cunning: 3, endurance: 1, wonder: 1 },
    personalitySummary: "You notice patterns under the floorboards. Patient, social, and unsettlingly good at timing, you know that the biggest changes begin as whispers in locked rooms.",
    reasoning: "Genestealer Cults reward ambush thinking: hidden pressure, sudden reversals, and the pleasure of revealing that the board was never as empty as it looked.",
    chronicleIntro: "The chronicle opens beneath the city, where chalk marks bloom on concrete like constellations. Above, the sirens have not started yet. Below, everyone is ready.",
    imagePrompt: "Underground concrete tunnels lit by purple work lamps, chalk constellations on walls, industrial pipes, dust motes and hidden alcoves, conspiratorial and tense, painterly, no people",
    cardQuote: "Everyone is ready.",
    palette: ["#0d0b12", "#3b2a54", "#d8c26a"],
  },
  {
    id: "towering-vow",
    name: "The Towering Vow",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Imperial Knights",
    profile: { valor: 2, discipline: 2, wonder: 1 },
    personalitySummary: "You like your promises large enough to cast a shadow. Honor matters to you not as decoration, but as architecture: something others can shelter beneath.",
    reasoning: "Imperial Knights appeal to players who want presence, drama, and decisive commitments. Every choice feels enormous because the army itself is a handful of walking oaths.",
    chronicleIntro: "The chronicle opens in a sunrise courtyard where banners stir above empty armor-plinths. Bells ring from the keep. A vow does not become smaller because it is old.",
    imagePrompt: "A vast feudal courtyard at sunrise, towering empty armor-plinths, long crimson and ivory banners, polished stone wet with morning light, noble and monumental, painterly, no people",
    cardQuote: "Promises cast shadows.",
    palette: ["#111018", "#5a2630", "#e0bd73"],
  },
  {
    id: "ashen-tithe",
    name: "The Ashen Tithe",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Chaos Knights",
    profile: { valor: 2, wildness: 2, endurance: 1 },
    personalitySummary: "You are not subtle about your dislikes, and there is a terrible honesty in that. When you enter a room, polite fictions look for somewhere else to stand.",
    reasoning: "Chaos Knights keep the towering drama but exchange ceremony for dread. They reward players who enjoy intimidation, pressure, and turning the table's attention into a weapon.",
    chronicleIntro: "The chronicle opens on a black field where old heraldry hangs in tatters from rusted gates. Thunder rolls without rain. Something enormous is owed.",
    imagePrompt: "A blackened battlefield of rusted gates and torn heraldic cloth, volcanic ash, sickly green lightning behind heavy clouds, oppressive scale and dread, painterly, no people",
    cardQuote: "Something enormous is owed.",
    palette: ["#0b0808", "#3a2a1f", "#9bd46a"],
  },
  {
    id: "silver-sanctum",
    name: "The Silver Sanctum",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Grey Knights",
    profile: { discipline: 3, wonder: 2, valor: 1 },
    personalitySummary: "You are private intensity. You do not need applause to do difficult things; you need the work to matter and the standard to be worthy of the effort.",
    reasoning: "Grey Knights fit players drawn to elite focus, ritual precision, and mystery. Their fantasy is not volume; it is a locked door opening only for the prepared.",
    chronicleIntro: "The chronicle opens in a sealed silver library where candles burn blue behind warded glass. A bell rings once. The hidden war has found its witness.",
    imagePrompt: "A sealed silver library with blue candlelight behind etched glass, marble floors, floating dust, geometric wards of light on high doors, secretive and sacred, painterly, no people",
    cardQuote: "The hidden war has found its witness.",
    palette: ["#0a0d12", "#344457", "#9fd8ff"],
  },
  {
    id: "auric-watch",
    name: "The Auric Watch",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Adeptus Custodes",
    profile: { discipline: 3, endurance: 2, valor: 1 },
    personalitySummary: "You are exacting because you care. Excellence, to you, is a form of loyalty — and you would rather hold one perfect line than win a sloppy mile.",
    reasoning: "Adeptus Custodes are for players who enjoy elite confidence, low model counts, and the satisfaction of each piece mattering. Their appeal is precision made regal.",
    chronicleIntro: "The chronicle opens before a golden gate at impossible scale. Nothing moves except the light. Waiting, here, is not inactivity. It is devotion sharpened over centuries.",
    imagePrompt: "An immense golden gate in a silent marble hall, warm light pooling across polished floors, red shadowed alcoves, perfect symmetry and solemn grandeur, painterly, no people",
    cardQuote: "Devotion sharpened.",
    palette: ["#120d06", "#6b4318", "#f0d37a"],
  },
  {
    id: "garden-of-rust",
    name: "The Garden of Rust",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Death Guard",
    profile: { endurance: 3, wildness: 1, wonder: 1 },
    personalitySummary: "You endure in ways that make other people uncomfortable. You can find humor in the rot, comfort in the ugly truth, and momentum in simply refusing to be moved.",
    reasoning: "Death Guard reward patience, durability, and a taste for grim inevitability. They suit players who enjoy watching the opponent's certainty slowly corrode.",
    chronicleIntro: "The chronicle opens in a greenhouse of broken glass, where flowers push through rusted machinery. The air is heavy, green, and strangely kind. Nothing clean lasts forever.",
    imagePrompt: "A ruined industrial greenhouse filled with rusted machinery and pallid green blooms, cracked glass roof, yellow fog, damp soil and corroded metal, melancholy and resilient, painterly, no people",
    cardQuote: "Certainty corrodes.",
    palette: ["#0d1008", "#4b4a22", "#b6c96a"],
  },
  {
    id: "sapphire-labyrinth",
    name: "The Sapphire Labyrinth",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "Thousand Sons",
    profile: { wonder: 3, cunning: 2, discipline: 1 },
    personalitySummary: "You cannot leave a locked idea alone. Knowledge pulls at you like a loose thread, and you are willing to unravel the sweater if the pattern underneath is beautiful enough.",
    reasoning: "Thousand Sons suit players drawn to arcane plans, layered tricks, and the danger of knowing too much. Their table identity feels like a puzzle box with a storm inside.",
    chronicleIntro: "The chronicle opens in a blue maze where every wall is a page and every page remembers being fire. You turn left because the whisper says right.",
    imagePrompt: "A sapphire maze of tiled walls covered in abstract golden script-like patterns, hovering lanterns, impossible stairways, violet sky above, mystical and cerebral, painterly, no people",
    cardQuote: "A puzzle box with a storm inside.",
    palette: ["#06101d", "#123d7a", "#d8b45a"],
  },
  {
    id: "red-urgency",
    name: "The Red Urgency",
    gameSystem: "Warhammer 40,000",
    primaryFaction: "World Eaters",
    profile: { valor: 3, wildness: 2 },
    personalitySummary: "You are allergic to dithering. When the moment comes, you want the door kicked open, the truth said plainly, and the next step close enough to bite.",
    reasoning: "World Eaters are for players who want direct pressure and explosive commitment. Their joy is momentum stripped of apology.",
    chronicleIntro: "The chronicle opens at the foot of a red canyon, drums echoing from stone to stone. There is a road ahead, but road is too gentle a word for it.",
    imagePrompt: "A red canyon under a furnace sky, dust storms curling through jagged stone, black iron braziers, harsh sunlight and kinetic heat, brutal and direct, painterly, no people",
    cardQuote: "Momentum without apology.",
    palette: ["#120606", "#6a1717", "#f06a32"],
  },
  {
    id: "skittering-crown",
    name: "The Skittering Crown",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Skaven",
    profile: { cunning: 3, wildness: 2 },
    personalitySummary: "You are a brilliant problem wearing too many ideas at once. Your mind moves through vents, shortcuts, and contingency plans, and somehow the ridiculous option keeps being the one that works.",
    reasoning: "Skaven reward players who enjoy swarms, schemes, volatility, and comic menace. Their victories feel like a machine held together by panic and genius finally doing exactly what it should.",
    chronicleIntro: "The chronicle opens in a clockwork sewer-city, all green sparks and whispering pipes. A thousand tiny plans collide overhead. One of them is yours, probably.",
    imagePrompt: "A vast underground clockwork sewer-city glowing with green sparks, tangled pipes, leaning gantries, oily water and nervous energy, sinister and absurd, painterly, no people",
    cardQuote: "Panic and genius.",
    palette: ["#080d0a", "#264329", "#7ee06a"],
  },
  {
    id: "star-coil",
    name: "The Star Coil",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Seraphon",
    profile: { wonder: 3, discipline: 2 },
    personalitySummary: "You think in constellations. While others chase the nearest noise, you look for the old pattern returning — patient, luminous, and too large to bully.",
    reasoning: "Seraphon fit players drawn to cosmic order, ancient mystery, and sudden celestial violence. Their appeal is strategy that feels written in starlight.",
    chronicleIntro: "The chronicle opens on a jungle observatory where wet stone mirrors the heavens. The stars are not distant tonight. They are instructions.",
    imagePrompt: "A stepped jungle observatory under brilliant constellations, wet jade stone, luminous pools, fern shadows and falling starlight, ancient and cosmic, painterly, no people",
    cardQuote: "The stars are instructions.",
    palette: ["#061512", "#1f5a4b", "#82e8ff"],
  },
  {
    id: "market-walls",
    name: "The Market Walls",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Cities of Sigmar",
    profile: { discipline: 2, endurance: 2, wonder: 1 },
    personalitySummary: "You believe civilization is a campfire that must be tended. You like messy coalitions, practical hope, and the small heroic work of keeping the lamps lit.",
    reasoning: "Cities of Sigmar suit players who enjoy combined arms, civic grit, and mortal courage in a mythic world. Their fantasy is community choosing to stand together.",
    chronicleIntro: "The chronicle opens at a city gate before dawn. Bakers, masons, scholars, and sentries all look toward the same road. The bell rings, and the walls answer.",
    imagePrompt: "A fortified fantasy city gate at dawn, market awnings folded beneath high walls, warm window lights, rain-slick cobbles and many different banners, hopeful and grounded, painterly, no people",
    cardQuote: "The walls answer.",
    palette: ["#0d1014", "#354256", "#d6a85f"],
  },
  {
    id: "sky-ledger",
    name: "The Sky Ledger",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Kharadron Overlords",
    profile: { cunning: 2, discipline: 2, wonder: 1 },
    personalitySummary: "You like contracts clear, tools reliable, and horizons profitable. Adventure is best when someone brought a map, a backup plan, and a receipt.",
    reasoning: "Kharadron Overlords reward careful movement, firepower, and audacious mobility. They suit players who enjoy clever logistics with a brass grin.",
    chronicleIntro: "The chronicle opens above the clouds, where dock-lanterns swing from brass pylons and every rope hums with altitude. The deal is risky. Good.",
    imagePrompt: "A brass sky-dock floating above clouds, mooring pylons, amber lanterns, taut cables, distant stormlight and polished metal, adventurous and mercantile, painterly, no people",
    cardQuote: "A brass grin at the horizon.",
    palette: ["#081018", "#4f3b22", "#f0b45f"],
  },
  {
    id: "ember-vault",
    name: "The Ember Vault",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Fyreslayers",
    profile: { valor: 2, endurance: 2, discipline: 1 },
    personalitySummary: "You are heat under stone: loyal, intense, and difficult to extinguish. If someone earns your trust, they get the whole furnace.",
    reasoning: "Fyreslayers fit players who enjoy fierce commitments, compact aggression, and oath-bound momentum. Their appeal is the feeling of a promise glowing hotter as pressure rises.",
    chronicleIntro: "The chronicle opens in a volcanic hold where gold light runs through black rock. The vault doors shake. Inside, the old promises wake red.",
    imagePrompt: "A volcanic mountain hold with black basalt vault doors, rivers of gold-orange light in stone channels, sparks and heat haze, fierce and oathbound, painterly, no people",
    cardQuote: "The whole furnace.",
    palette: ["#120805", "#5a2112", "#ff9a3d"],
  },
  {
    id: "dawn-prism",
    name: "The Dawn Prism",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Lumineth Realm-lords",
    profile: { discipline: 2, wonder: 2, cunning: 1 },
    personalitySummary: "You want beauty to be exact. You polish ideas until they catch the light, and you know serenity is often the hardest discipline in the room.",
    reasoning: "Lumineth Realm-lords suit players drawn to elegance, balance, and luminous precision. Their armies feel like a philosophy with sharpened edges.",
    chronicleIntro: "The chronicle opens on a white causeway over a mirror-lake. Mountains blush with first light. Every step asks whether you can be as clear as the dawn.",
    imagePrompt: "A white stone causeway over a mirror-still lake at dawn, pale mountains, prismatic light, slender towers and clean reflections, serene and exacting, painterly, no people",
    cardQuote: "Serenity is discipline.",
    palette: ["#071118", "#31506a", "#f2e6a0"],
  },
  {
    id: "crimson-oracle",
    name: "The Crimson Oracle",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Daughters of Khaine",
    profile: { valor: 2, cunning: 2, wonder: 1 },
    personalitySummary: "You trust intensity when it has a purpose. You can be graceful, social, even charming — but underneath is a blade of decision that does not ask twice.",
    reasoning: "Daughters of Khaine reward speed, ritual pressure, and decisive aggression. They suit players who want elegance that still leaves marks.",
    chronicleIntro: "The chronicle opens in a red temple mirrored by dark water. Silk moves without wind. The oracle smiles, and every candle leans closer.",
    imagePrompt: "A crimson temple reflected in black water, silk veils, obsidian steps, candlelight and sharp shadows, ritualistic and elegant, painterly, no people",
    cardQuote: "Elegance leaves marks.",
    palette: ["#12070d", "#5c1832", "#f07a8a"],
  },
  {
    id: "hollow-bell",
    name: "The Hollow Bell",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Nighthaunt",
    profile: { wonder: 2, endurance: 2, cunning: 1 },
    personalitySummary: "You understand the power of atmosphere. A pause, a memory, an unfinished sentence — these are tools, and you know how loudly absence can speak.",
    reasoning: "Nighthaunt suit players drawn to haunting movement, eerie resilience, and the feeling of dread arriving through walls. Their playstyle is pressure as a ghost story.",
    chronicleIntro: "The chronicle opens on a drowned road where bells ring under the mist. No hand pulls the ropes. The sound remembers you anyway.",
    imagePrompt: "A drowned cobblestone road in moonlit mist, leaning bell towers, pale blue lantern glow, still water and drifting veils of fog, mournful and uncanny, painterly, no people",
    cardQuote: "Absence speaks loudly.",
    palette: ["#061013", "#1d3a45", "#a8f0e8"],
  },
  {
    id: "bone-accounting",
    name: "The Bone Accounting",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Ossiarch Bonereapers",
    profile: { discipline: 3, endurance: 2 },
    personalitySummary: "You appreciate structure, consequences, and ledgers that balance. Mercy is admirable; efficiency is dependable. You prefer systems that do not forget what they are owed.",
    reasoning: "Ossiarch Bonereapers reward methodical pressure, durability, and organized inevitability. They suit players who enjoy making the battlefield feel audited.",
    chronicleIntro: "The chronicle opens in a silent archive of ivory pillars. Every step echoes like a stamp on parchment. The account was opened long before you arrived.",
    imagePrompt: "A silent necropolis archive of ivory pillars and black stone floors, cold amber braziers, stacked tablets, symmetrical avenues, severe and inevitable, painterly, no people",
    cardQuote: "The account remains open.",
    palette: ["#0d0c0a", "#4a4032", "#d8c190"],
  },
  {
    id: "iron-tempest",
    name: "The Iron Tempest",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Slaves to Darkness",
    profile: { valor: 2, endurance: 2, wildness: 1 },
    personalitySummary: "You are drawn to the road that tests you. Comfort is fine for other people; you want the storm, the climb, and the proof that you did not turn aside.",
    reasoning: "Slaves to Darkness suit players who enjoy grim momentum, armored presence, and the mythic weight of choosing power at a cost.",
    chronicleIntro: "The chronicle opens on a mountain pass under black snow. Far above, iron bells swing in the gale. The path does not welcome you. Perfect.",
    imagePrompt: "A black mountain pass in a snowstorm, iron bells on broken posts, dark fortress lights above cliffs, wind and ash, harsh and mythic, painterly, no people",
    cardQuote: "The path tests you.",
    palette: ["#09090c", "#30303a", "#b6a06a"],
  },
  {
    id: "brass-thunder",
    name: "The Brass Thunder",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Blades of Khorne",
    profile: { valor: 3, discipline: 1, wildness: 1 },
    personalitySummary: "You respect action over speeches. Anger, to you, is not a mess if it has a direction; it is weather with a destination.",
    reasoning: "Blades of Khorne reward direct aggression, ritualized violence, and relentless tempo. They suit players who want the battle plan written in exclamation points.",
    chronicleIntro: "The chronicle opens on a brass causeway over red clouds. War-drums shake the bolts loose. The gate ahead is not locked for long.",
    imagePrompt: "A brass causeway over red storm clouds, rune-like geometric inlays, huge locked gate, sparks and drumlike thunder, relentless and hot, painterly, no people",
    cardQuote: "Weather with a destination.",
    palette: ["#130605", "#6b1810", "#e0a13d"],
  },
  {
    id: "changing-stair",
    name: "The Changing Stair",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Disciples of Tzeentch",
    profile: { wonder: 3, cunning: 2 },
    personalitySummary: "You delight in possibilities. Plans are living things to you, best when they sprout doors, mirrors, and a little harmless impossible geometry.",
    reasoning: "Disciples of Tzeentch suit players who love magic, misdirection, and layered contingencies. Their appeal is watching a scheme become more real than the floor.",
    chronicleIntro: "The chronicle opens on a staircase that changes color whenever you lie to it. At the top is a door you remember from a dream you have not had yet.",
    imagePrompt: "An impossible floating staircase twisting through turquoise and pink clouds, mirrored doors, lanterns of blue fire, shifting geometry, strange and luminous, painterly, no people",
    cardQuote: "Possibility sprouts doors.",
    palette: ["#070a18", "#283c8a", "#ff7ad8"],
  },
  {
    id: "rain-of-spores",
    name: "The Rain of Spores",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Maggotkin of Nurgle",
    profile: { endurance: 3, wonder: 1, wildness: 1 },
    personalitySummary: "You are unnervingly good at accepting reality and continuing anyway. Where others see a mess, you see compost, patience, and the beginning of something green.",
    reasoning: "Maggotkin of Nurgle reward resilience, board presence, and a weirdly cheerful inevitability. They fit players who like decay presented as abundance.",
    chronicleIntro: "The chronicle opens in warm rain over a mossy ruin. Mushrooms bead with gold water. The stones are falling apart, yes — and blooming beautifully.",
    imagePrompt: "A moss-covered ruin in warm rain, oversized mushrooms, golden puddles, soft green fog, cracked stones blooming with life, grotesque yet gentle, painterly, no people",
    cardQuote: "Decay as abundance.",
    palette: ["#0b1108", "#3f5126", "#d6c66a"],
  },
  {
    id: "velvet-mirror",
    name: "The Velvet Mirror",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Hedonites of Slaanesh",
    profile: { wonder: 2, cunning: 2, wildness: 1 },
    personalitySummary: "You are sensitive to texture: music, mood, timing, the difference between enough and too much. Naturally, you are fascinated by too much.",
    reasoning: "Hedonites of Slaanesh suit players who enjoy speed, temptation, and exquisite risk. Their appeal is excess balanced on a knife-edge.",
    chronicleIntro: "The chronicle opens in a palace of velvet echoes and mirrored floors. Every hallway offers applause. Every reflection asks for one more step.",
    imagePrompt: "A decadent mirrored palace with violet velvet drapes, rose-gold light, polished floors, distant fountains and soft haze, alluring and dangerous, painterly, no people",
    cardQuote: "One more step.",
    palette: ["#120714", "#4b1d55", "#f0a0c8"],
  },
  {
    id: "winter-cauldron",
    name: "The Winter Cauldron",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Ogor Mawtribes",
    profile: { wildness: 2, endurance: 2, valor: 1 },
    personalitySummary: "You trust appetite: for food, stories, movement, and a life big enough to leave tracks. Subtlety has its uses, but so does arriving like weather.",
    reasoning: "Ogor Mawtribes reward momentum, impact, and hearty resilience. They suit players who want the board to feel smaller every time they advance.",
    chronicleIntro: "The chronicle opens beside a huge iron cauldron in a snow camp. The wind howls. The stew bubbles. The mountains look edible from here.",
    imagePrompt: "A snowy mountain camp around a huge iron cauldron, warm firelight, heavy tracks in snow, hide tents and blue twilight, hearty and primal, painterly, no people",
    cardQuote: "Arrive like weather.",
    palette: ["#091018", "#35475a", "#e89a4a"],
  },
  {
    id: "green-avalanche",
    name: "The Green Avalanche",
    gameSystem: "Warhammer: Age of Sigmar",
    primaryFaction: "Orruk Warclans",
    profile: { valor: 3, wildness: 2 },
    personalitySummary: "You are momentum with a grin. Competition wakes you up, noise makes you better, and sometimes the best plan is the one that starts before doubt can get its boots on.",
    reasoning: "Orruk Warclans suit players who enjoy brawling energy, bold advances, and contagious confidence. Their appeal is simple: the horizon is there to be crashed into.",
    chronicleIntro: "The chronicle opens on a ridge of green thunderclouds above a trampled plain. Drums answer drums. The horizon makes a terrible tactical mistake: existing.",
    imagePrompt: "A stormy green horizon over a trampled plain, crude standing stones, muddy tracks, lightning through low clouds, rowdy and unstoppable, painterly, no people",
    cardQuote: "Momentum with a grin.",
    palette: ["#071008", "#24451e", "#9ad45a"],
  },
];

export const BANNER_BY_ID = new Map(BANNERS.map((b) => [b.id, b] as const));
