// Banner ids that have an AI-rendered raster plate under public/plates/.
// Regenerated by scripts/generate-plates.mjs — don't edit by hand.
// While empty, BannerArt uses the hand-crafted SVG plates
// (components/chronicle/plates.tsx).
export const RASTER_PLATES: Set<string> = new Set([]);
export const RASTER_EXT: Record<string, string> = {};
