// One-time generator for AI-rendered banner plates (OpenAI gpt-image-1).
//
// Usage:
//   OPENAI_API_KEY=sk-... node scripts/generate-plates.mjs            # all missing
//   OPENAI_API_KEY=sk-... node scripts/generate-plates.mjs --force    # regenerate all
//   OPENAI_API_KEY=sk-... node scripts/generate-plates.mjs cracked-moon veiled-path
//
// For each banner it renders the banner's art direction (environments and
// mood only — no characters, no publisher IP) to public/plates/<id>.png,
// then rewrites lib/chronicle/raster-plates.ts so BannerArt prefers the
// raster over the hand-crafted SVG. Commit the images + manifest together.
//
// Run once per new banner, not per visitor — plates are static assets.
// Tip: convert to webp afterwards if you have cwebp installed:
//   for f in public/plates/*.png; do cwebp -q 82 "$f" -o "${f%.png}.webp" && rm "$f"; done
// (the manifest writer below detects whichever extension exists)

import { readdirSync, mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import path from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const PLATES_DIR = path.join(ROOT, "public", "plates");
const MANIFEST = path.join(ROOT, "lib", "chronicle", "raster-plates.ts");

// Keep in sync with lib/chronicle/banners.ts (id + imagePrompt). Parsed from
// the source so there is one source of truth:
const bannersSource = readFileSync(
  path.join(ROOT, "lib", "chronicle", "banners.ts"),
  "utf8"
);
const banners = [...bannersSource.matchAll(/id:\s*"([^"]+)"[\s\S]*?imagePrompt:\s*\n?\s*"([^"]+)"/g)].map(
  ([, id, imagePrompt]) => ({ id, imagePrompt })
);

const STYLE =
  "Dark, elegant, atmospheric, premium fantasy illustration in muted tones with a single strong light source. Aged campaign-journal plate, painterly, cinematic depth. Strictly no characters, no creatures, no logos, no text, no watermarks.";

const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error("Set OPENAI_API_KEY to generate plates.");
  process.exit(1);
}
if (banners.length === 0) {
  console.error("Could not parse banners from lib/chronicle/banners.ts");
  process.exit(1);
}

const force = process.argv.includes("--force");
const only = process.argv.slice(2).filter((a) => !a.startsWith("--"));
mkdirSync(PLATES_DIR, { recursive: true });

async function generate(banner) {
  const res = await fetch("https://api.openai.com/v1/images/generations", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "gpt-image-1",
      prompt: `${banner.imagePrompt}. ${STYLE}`,
      size: "1024x1536", // portrait, matches the reveal hero crop
      quality: "high",
      output_format: "png",
    }),
  });
  if (!res.ok) {
    throw new Error(`${banner.id}: HTTP ${res.status} — ${await res.text()}`);
  }
  const data = await res.json();
  const b64 = data.data?.[0]?.b64_json;
  if (!b64) throw new Error(`${banner.id}: no image in response`);
  const out = path.join(PLATES_DIR, `${banner.id}.png`);
  writeFileSync(out, Buffer.from(b64, "base64"));
  console.log(`✦ ${banner.id} → ${path.relative(ROOT, out)}`);
}

function writeManifest() {
  const files = existsSync(PLATES_DIR) ? readdirSync(PLATES_DIR) : [];
  const ids = banners
    .map((b) => b.id)
    .filter((id) => files.some((f) => f === `${id}.webp` || f === `${id}.png`));
  const ext = Object.fromEntries(
    ids.map((id) => [id, files.includes(`${id}.webp`) ? "webp" : "png"])
  );
  writeFileSync(
    MANIFEST,
    [
      "// Banner ids that have an AI-rendered raster plate under public/plates/.",
      "// Regenerated by scripts/generate-plates.mjs — don't edit by hand.",
      `export const RASTER_PLATES: Set<string> = new Set(${JSON.stringify(ids, null, 2)});`,
      `export const RASTER_EXT: Record<string, string> = ${JSON.stringify(ext, null, 2)};`,
      "",
    ].join("\n")
  );
  console.log(`Manifest updated: ${ids.length} raster plate(s).`);
}

const targets = banners.filter((b) => {
  if (only.length) return only.includes(b.id);
  if (force) return true;
  return (
    !existsSync(path.join(PLATES_DIR, `${b.id}.png`)) &&
    !existsSync(path.join(PLATES_DIR, `${b.id}.webp`))
  );
});

console.log(`Generating ${targets.length} plate(s)…`);
for (const banner of targets) {
  try {
    await generate(banner);
  } catch (err) {
    console.error(String(err));
  }
}
writeManifest();
